# Generated by Django 5.0.6 on 2024-05-28 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 5, 9, 39, 207967, tzinfo=datetime.timezone.utc)),
        ),
    ]
