# Generated by Django 5.0.6 on 2024-05-28 05:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_team_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 5, 59, 46, 811913, tzinfo=datetime.timezone.utc)),
        ),
    ]
