# Generated by Django 5.0.6 on 2024-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_match_match_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registration_deadline',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_close_for_register',
            field=models.BooleanField(default=False),
        ),
    ]
